---
- name: Pull Docker image of ScientificCalculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Pull image ScientificCalculator
      docker_image:
        name: slr1999/scientific_calculator:latest
        source: pull